/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    'post-view-metrics': PostViewMetric;
    'post-view-dedupe': PostViewDedupe;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    posts: {
      ownedMedia: 'media';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'post-view-metrics': PostViewMetricsSelect<false> | PostViewMetricsSelect<true>;
    'post-view-dedupe': PostViewDedupeSelect<false> | PostViewDedupeSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('zh-Hans' | 'en') | ('zh-Hans' | 'en')[];
  globals: {
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: 'zh-Hans' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  roles: ('admin' | 'editor')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  credit?: string | null;
  previewSVGStatus?: ('pending' | 'ready' | 'failed') | null;
  previewSVGURL?: string | null;
  previewSVGFilename?: string | null;
  previewSVGError?: string | null;
  previewSVGGeneratedAt?: string | null;
  importKey?: string | null;
  ownerPost?: (number | null) | Post;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  excerpt?: string | null;
  /**
   * Markdown is supported here, including blockquotes, fenced code, tables, GitHub-style callouts via > [!NOTE], and citations via [@citation-key].
   */
  content: string;
  ownedMedia?: {
    docs?: (number | Media)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  heroImage?: (number | null) | Media;
  /**
   * Store one BibTeX source directly on this post. Structured editing is available for safe, common entries.
   */
  bibliography?: {
    /**
     * Optional original filename for the BibTeX source stored on this post.
     */
    filename?: string | null;
    /**
     * Paste BibTeX source here. Citation keys used in the current locale content are validated against this text.
     */
    source?: string | null;
  };
  attachments?:
    | {
        file: number | Media;
        label?: string | null;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  translationStatus?: ('original' | 'machine' | 'reviewed') | null;
  translatedFromLocale?: string | null;
  translatedAt?: string | null;
  translationProvider?: string | null;
  seo?: {
    /**
     * Optional SEO title override for the current locale. Leave blank to reuse the post title.
     */
    metaTitle?: string | null;
    /**
     * Optional SEO description override for the current locale. Leave blank to reuse the excerpt or a summary derived from the post body.
     */
    metaDescription?: string | null;
    /**
     * Optional social sharing image override. Leave blank to reuse the hero image, then the site default image.
     */
    metaImage?: (number | null) | Media;
    /**
     * Prevent this locale from appearing in search results or the sitemap. Leave disabled for normal published posts.
     */
    noindex?: boolean | null;
  };
  slug: string;
  tags?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-view-metrics".
 */
export interface PostViewMetric {
  id: number;
  metricKey: string;
  post: number | Post;
  locale: 'zh-Hans' | 'en';
  viewCount: number;
  rawHits: number;
  uniqueVisitors: number;
  lastViewedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-view-dedupe".
 */
export interface PostViewDedupe {
  id: number;
  dedupeKey: string;
  post: number | Post;
  locale: 'zh-Hans' | 'en';
  firstSeenAt: string;
  lastSeenAt: string;
  expiresAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'post-view-metrics';
        value: number | PostViewMetric;
      } | null)
    | ({
        relationTo: 'post-view-dedupe';
        value: number | PostViewDedupe;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  credit?: T;
  previewSVGStatus?: T;
  previewSVGURL?: T;
  previewSVGFilename?: T;
  previewSVGError?: T;
  previewSVGGeneratedAt?: T;
  importKey?: T;
  ownerPost?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  content?: T;
  ownedMedia?: T;
  heroImage?: T;
  bibliography?:
    | T
    | {
        filename?: T;
        source?: T;
      };
  attachments?:
    | T
    | {
        file?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  translationStatus?: T;
  translatedFromLocale?: T;
  translatedAt?: T;
  translationProvider?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        metaImage?: T;
        noindex?: T;
      };
  slug?: T;
  tags?:
    | T
    | {
        value?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-view-metrics_select".
 */
export interface PostViewMetricsSelect<T extends boolean = true> {
  metricKey?: T;
  post?: T;
  locale?: T;
  viewCount?: T;
  rawHits?: T;
  uniqueVisitors?: T;
  lastViewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "post-view-dedupe_select".
 */
export interface PostViewDedupeSelect<T extends boolean = true> {
  dedupeKey?: T;
  post?: T;
  locale?: T;
  firstSeenAt?: T;
  lastSeenAt?: T;
  expiresAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Configure the homepage hero copy and the structured footer content shown on the frontend.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  homeHero?: {
    eyebrow?: string | null;
    title?: string | null;
    description?: string | null;
  };
  seo?: {
    /**
     * Optional SEO title override for the localized homepage. Leave blank to reuse the homepage hero title.
     */
    homeTitle?: string | null;
    /**
     * Optional SEO description override for the localized homepage. Leave blank to reuse the site description.
     */
    homeDescription?: string | null;
    defaultSocialImage?: (number | null) | Media;
  };
  /**
   * Configure the code-owned article design preset and a small set of safe spacing overrides.
   */
  articleLayout: {
    /**
     * Choose the default article design preset for public article pages.
     */
    preset: 'compact-editorial' | 'balanced-editorial' | 'current';
    /**
     * Optional font stack overrides. Leave blank to inherit the selected design preset.
     */
    typography?: {
      /**
       * Western body text font stack.
       */
      latinFont?: ('source-sans-3' | 'inter' | 'newsreader') | null;
      /**
       * Chinese body text fallback stack.
       */
      cjkFont?: ('noto-sans-sc' | 'noto-serif-sc' | 'system-cjk-sans') | null;
      /**
       * Heading font stack. The default keeps headings in a serif voice.
       */
      headingFont?: ('editorial-serif' | 'body-sans') | null;
      /**
       * Inline and block code font stack.
       */
      codeFont?: ('jetbrains-mono' | 'system-mono') | null;
    };
    /**
     * Optional safe CSS token overrides. Leave blank to use the selected preset values.
     */
    advanced?: {
      /**
       * Controls both the reading column and prose max width, such as 76ch.
       */
      contentWidth?: string | null;
      /**
       * Body text size, such as 0.98rem or 17px.
       */
      bodyFontSize?: string | null;
      /**
       * Unitless body line-height ratio, such as 1.65.
       */
      bodyLineHeight?: string | null;
      /**
       * Vertical gap between consecutive paragraphs, such as 0.75rem.
       */
      paragraphGap?: string | null;
      /**
       * Default vertical flow gap between ordinary article elements.
       */
      flowGap?: string | null;
      /**
       * Outer vertical gap for figures, tables, code blocks, and callouts.
       */
      blockGap?: string | null;
      /**
       * Internal gap between media/table surfaces and their captions.
       */
      captionGap?: string | null;
      /**
       * Desktop gap between the reading column and the table of contents rail.
       */
      gridGap?: string | null;
    };
  };
  footer: {
    /**
     * Controls the frontend footer layout. Preview every option under /dev/footer-layouts.
     */
    layoutStyle: 'compact' | 'directory' | 'ledger' | 'balanced';
    brand: {
      logo?: (number | null) | Media;
      name?: string | null;
      description?: string | null;
      supportingText?: string | null;
      link: {
        type: 'internal' | 'external';
        /**
         * Enter a locale-agnostic path such as /posts or /about.
         */
        internalPath?: string | null;
        externalUrl?: string | null;
        openInNewTab?: boolean | null;
      };
    };
    navigationSections?:
      | {
          title: string;
          links?:
            | {
                label: string;
                description?: string | null;
                link: {
                  type: 'internal' | 'external';
                  /**
                   * Enter a locale-agnostic path such as /posts or /about.
                   */
                  internalPath?: string | null;
                  externalUrl?: string | null;
                  openInNewTab?: boolean | null;
                };
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
    socialLinks?:
      | {
          platform: 'github' | 'x' | 'linkedin' | 'youtube' | 'instagram' | 'discord' | 'rss' | 'email' | 'other';
          label?: string | null;
          url: string;
          openInNewTab?: boolean | null;
          id?: string | null;
        }[]
      | null;
    contactItems?:
      | {
          label: string;
          value: string;
          link: {
            type: 'internal' | 'external';
            /**
             * Enter a locale-agnostic path such as /posts or /about.
             */
            internalPath?: string | null;
            externalUrl?: string | null;
            openInNewTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    legalLinks?:
      | {
          label: string;
          link: {
            type: 'internal' | 'external';
            /**
             * Enter a locale-agnostic path such as /posts or /about.
             */
            internalPath?: string | null;
            externalUrl?: string | null;
            openInNewTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    compliance?: {
      copyright?: string | null;
      filings?:
        | {
            label: string;
            value: string;
            href?: string | null;
            id?: string | null;
          }[]
        | null;
    };
    bottomBar?: {
      note?: string | null;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  homeHero?:
    | T
    | {
        eyebrow?: T;
        title?: T;
        description?: T;
      };
  seo?:
    | T
    | {
        homeTitle?: T;
        homeDescription?: T;
        defaultSocialImage?: T;
      };
  articleLayout?:
    | T
    | {
        preset?: T;
        typography?:
          | T
          | {
              latinFont?: T;
              cjkFont?: T;
              headingFont?: T;
              codeFont?: T;
            };
        advanced?:
          | T
          | {
              contentWidth?: T;
              bodyFontSize?: T;
              bodyLineHeight?: T;
              paragraphGap?: T;
              flowGap?: T;
              blockGap?: T;
              captionGap?: T;
              gridGap?: T;
            };
      };
  footer?:
    | T
    | {
        layoutStyle?: T;
        brand?:
          | T
          | {
              logo?: T;
              name?: T;
              description?: T;
              supportingText?: T;
              link?:
                | T
                | {
                    type?: T;
                    internalPath?: T;
                    externalUrl?: T;
                    openInNewTab?: T;
                  };
            };
        navigationSections?:
          | T
          | {
              title?: T;
              links?:
                | T
                | {
                    label?: T;
                    description?: T;
                    link?:
                      | T
                      | {
                          type?: T;
                          internalPath?: T;
                          externalUrl?: T;
                          openInNewTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
            };
        socialLinks?:
          | T
          | {
              platform?: T;
              label?: T;
              url?: T;
              openInNewTab?: T;
              id?: T;
            };
        contactItems?:
          | T
          | {
              label?: T;
              value?: T;
              link?:
                | T
                | {
                    type?: T;
                    internalPath?: T;
                    externalUrl?: T;
                    openInNewTab?: T;
                  };
              id?: T;
            };
        legalLinks?:
          | T
          | {
              label?: T;
              link?:
                | T
                | {
                    type?: T;
                    internalPath?: T;
                    externalUrl?: T;
                    openInNewTab?: T;
                  };
              id?: T;
            };
        compliance?:
          | T
          | {
              copyright?: T;
              filings?:
                | T
                | {
                    label?: T;
                    value?: T;
                    href?: T;
                    id?: T;
                  };
            };
        bottomBar?:
          | T
          | {
              note?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'posts';
      value: number | Post;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}